CREATE TABLE `tab_operation_log` (
    `id`                 BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键 id',
    `module`             VARCHAR(32)  NOT NULL COMMENT '业务模块中文名，如"组织管理"',
    `resource_type`      VARCHAR(32)  NOT NULL COMMENT '资源类型编码，如 org/user/position/app/role/permission/admin/menu/dictType/dictItem',
    `resource_name`      VARCHAR(32)  NOT NULL COMMENT '资源类型中文名，如"组织"',
    `operation_type`     INT          NOT NULL COMMENT '操作类型：1=新增，2=编辑，3=启用，4=停用，5=删除',
    `target_id`          BIGINT       NOT NULL COMMENT '被操作对象主键 id',
    `target_name`        VARCHAR(128) NOT NULL COMMENT '被操作对象名称快照，即使对象后续被改名/删除也保留操作当时的名称',
    `change_detail`      TEXT         NOT NULL COMMENT '字段变更详情，JSON 数组，每项 {field,oldValue,newValue}',
    `operate_ip`         VARCHAR(64)  DEFAULT NULL COMMENT '操作发起 IP，从当前 HTTP 请求自动获取，取不到（如非 HTTP 上下文中调用）时为空',
    `operate_terminal`   VARCHAR(32)  DEFAULT NULL COMMENT '操作终端类型，如 PC/Mobile/Tablet，从 User-Agent 解析，解析不出时为空',
    `operate_os`         VARCHAR(64)  DEFAULT NULL COMMENT '操作系统，如 Windows 10/macOS/Android，从 User-Agent 解析，解析不出时为空',
    `operate_browser`    VARCHAR(64)  DEFAULT NULL COMMENT '操作浏览器，如 Chrome 120，从 User-Agent 解析，解析不出时为空',
    `operate_user_agent` VARCHAR(512) DEFAULT NULL COMMENT '原始 User-Agent 请求头，取不到时为空',
    `create_by`          VARCHAR(64)  NOT NULL COMMENT '操作人，即创建人',
    `create_time`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间，即创建时间',
    `update_by`          VARCHAR(64)  NOT NULL COMMENT '更新人，日志不可变更，恒等于 create_by',
    `update_time`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间，日志不可变更，恒等于 create_time',
    PRIMARY KEY (`id`),
    KEY `idx_tab_operation_log_resource` (`resource_type`, `target_id`),
    KEY `idx_tab_operation_log_module` (`module`),
    KEY `idx_tab_operation_log_create_by` (`create_by`),
    KEY `idx_tab_operation_log_create_time` (`create_time`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '操作日志表，只追加不更新不删除';
