-- ----------------------------------------------------------------------------
-- 元数据字段配置模块 - 为 tab_user、tab_user_position、tab_app 补齐扩展字段
-- （Flyway 迁移版本 V17），与 tab_org 已有的 ext1~ext10 保持一致，使四类业务
-- 对象在扩展字段能力上保持一致，供后续"元数据字段配置 + 表单字段定义"体系
-- 纳入可配置范围。
-- ----------------------------------------------------------------------------

-- ALTER TABLE `tab_user`
--     ADD COLUMN `ext1` VARCHAR(255) NULL COMMENT '预留扩展字段 1，暂不使用' AFTER `status`,
--     ADD COLUMN `ext2` VARCHAR(255) NULL COMMENT '预留扩展字段 2，暂不使用' AFTER `ext1`,
--     ADD COLUMN `ext3` VARCHAR(255) NULL COMMENT '预留扩展字段 3，暂不使用' AFTER `ext2`,
--     ADD COLUMN `ext4` VARCHAR(255) NULL COMMENT '预留扩展字段 4，暂不使用' AFTER `ext3`,
--     ADD COLUMN `ext5` VARCHAR(255) NULL COMMENT '预留扩展字段 5，暂不使用' AFTER `ext4`,
--     ADD COLUMN `ext6` VARCHAR(255) NULL COMMENT '预留扩展字段 6，暂不使用' AFTER `ext5`,
--     ADD COLUMN `ext7` VARCHAR(255) NULL COMMENT '预留扩展字段 7，暂不使用' AFTER `ext6`,
--     ADD COLUMN `ext8` VARCHAR(255) NULL COMMENT '预留扩展字段 8，暂不使用' AFTER `ext7`,
--     ADD COLUMN `ext9` VARCHAR(255) NULL COMMENT '预留扩展字段 9，暂不使用' AFTER `ext8`,
--     ADD COLUMN `ext10` VARCHAR(255) NULL COMMENT '预留扩展字段 10，暂不使用' AFTER `ext9`;

-- ALTER TABLE `tab_user_position`
--     ADD COLUMN `ext1` VARCHAR(255) NULL COMMENT '预留扩展字段 1，暂不使用' AFTER `status`,
--     ADD COLUMN `ext2` VARCHAR(255) NULL COMMENT '预留扩展字段 2，暂不使用' AFTER `ext1`,
--     ADD COLUMN `ext3` VARCHAR(255) NULL COMMENT '预留扩展字段 3，暂不使用' AFTER `ext2`,
--     ADD COLUMN `ext4` VARCHAR(255) NULL COMMENT '预留扩展字段 4，暂不使用' AFTER `ext3`,
--     ADD COLUMN `ext5` VARCHAR(255) NULL COMMENT '预留扩展字段 5，暂不使用' AFTER `ext4`,
--     ADD COLUMN `ext6` VARCHAR(255) NULL COMMENT '预留扩展字段 6，暂不使用' AFTER `ext5`,
--     ADD COLUMN `ext7` VARCHAR(255) NULL COMMENT '预留扩展字段 7，暂不使用' AFTER `ext6`,
--     ADD COLUMN `ext8` VARCHAR(255) NULL COMMENT '预留扩展字段 8，暂不使用' AFTER `ext7`,
--     ADD COLUMN `ext9` VARCHAR(255) NULL COMMENT '预留扩展字段 9，暂不使用' AFTER `ext8`,
--     ADD COLUMN `ext10` VARCHAR(255) NULL COMMENT '预留扩展字段 10，暂不使用' AFTER `ext9`;

-- ALTER TABLE `tab_app`
--     ADD COLUMN `ext1` VARCHAR(255) NULL COMMENT '预留扩展字段 1，暂不使用' AFTER `status`,
--     ADD COLUMN `ext2` VARCHAR(255) NULL COMMENT '预留扩展字段 2，暂不使用' AFTER `ext1`,
--     ADD COLUMN `ext3` VARCHAR(255) NULL COMMENT '预留扩展字段 3，暂不使用' AFTER `ext2`,
--     ADD COLUMN `ext4` VARCHAR(255) NULL COMMENT '预留扩展字段 4，暂不使用' AFTER `ext3`,
--     ADD COLUMN `ext5` VARCHAR(255) NULL COMMENT '预留扩展字段 5，暂不使用' AFTER `ext4`,
--     ADD COLUMN `ext6` VARCHAR(255) NULL COMMENT '预留扩展字段 6，暂不使用' AFTER `ext5`,
--     ADD COLUMN `ext7` VARCHAR(255) NULL COMMENT '预留扩展字段 7，暂不使用' AFTER `ext6`,
--     ADD COLUMN `ext8` VARCHAR(255) NULL COMMENT '预留扩展字段 8，暂不使用' AFTER `ext7`,
--     ADD COLUMN `ext9` VARCHAR(255) NULL COMMENT '预留扩展字段 9，暂不使用' AFTER `ext8`,
--     ADD COLUMN `ext10` VARCHAR(255) NULL COMMENT '预留扩展字段 10，暂不使用' AFTER `ext9`;
