CREATE TABLE `tab_app` (
    `id`          BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键 id',
    `name`        VARCHAR(64)  NOT NULL COMMENT '应用名称',
    `code`        VARCHAR(64)  NOT NULL COMMENT '应用编码',
    `owner_id`    BIGINT       NOT NULL COMMENT '负责人用户 id',
    `org_id`      BIGINT       NOT NULL COMMENT '所属组织 id',
    `show_order`  INT          NOT NULL DEFAULT 0 COMMENT '显示序号，值越大越靠前',
    `remark`      VARCHAR(255)          DEFAULT NULL COMMENT '备注',
    `status`      INT          NOT NULL DEFAULT 2000 COMMENT '状态：2000=启用，3000=停用，-1000=已删除（逻辑删除）',
    `ext1`        VARCHAR(255) NULL COMMENT '预留扩展字段 1，暂不使用',
    `ext2`        VARCHAR(255) NULL COMMENT '预留扩展字段 2，暂不使用',
    `ext3`        VARCHAR(255) NULL COMMENT '预留扩展字段 3，暂不使用',
    `ext4`        VARCHAR(255) NULL COMMENT '预留扩展字段 4，暂不使用',
    `ext5`        VARCHAR(255) NULL COMMENT '预留扩展字段 5，暂不使用',
    `ext6`        VARCHAR(255) NULL COMMENT '预留扩展字段 6，暂不使用',
    `ext7`        VARCHAR(255) NULL COMMENT '预留扩展字段 7，暂不使用',
    `ext8`        VARCHAR(255) NULL COMMENT '预留扩展字段 8，暂不使用',
    `ext9`        VARCHAR(255) NULL COMMENT '预留扩展字段 9，暂不使用',
    `ext10`       VARCHAR(255) NULL COMMENT '预留扩展字段 10，暂不使用',
    `create_by`   VARCHAR(64)           DEFAULT NULL COMMENT '创建人',
    `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by`   VARCHAR(64)           DEFAULT NULL COMMENT '更新人',
    `update_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_tab_app_owner_id` (`owner_id`),
    KEY `idx_tab_app_org_id` (`org_id`),
    KEY `idx_tab_app_code` (`code`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '应用主数据表';
